# Generated by Django 5.2.4 on 2025-07-15 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('year', models.CharField(max_length=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.floor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BedSpace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150)),
                ('number_of_beds', models.PositiveIntegerField()),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.hall')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('fullname', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=16, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('marital_status', models.CharField(max_length=20)),
                ('num_children_below_10', models.PositiveIntegerField(default=0)),
                ('names_of_children', models.TextField(blank=True, null=True)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('arrival_date', models.DateField()),
                ('disability_or_allergy', models.TextField(blank=True, null=True)),
                ('local_assembly', models.CharField(max_length=150)),
                ('local_assembly_address', models.TextField()),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.program')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
